name: Adromeda E-commerce CI/CD
run-name: ${{github.actor}}'s workflow
on: 
  push : 
    on : 
      tags: - "v*"

jobs:
  build-run-andromeda:
    runs-on: ubuntu-latest
    steps:
        - name : Checkout Source Code
          uses: actions/checkout@v6

        - name : Login to Container Registry
          uses: docker/login-action@v4
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Push Docker App to Container Registry
          uses : docker/build-push-action@v7
          with:
            context: .
            push: true
            tags: ghcr.io/andromeda:v1.0.0
